---
- name: Reboot host
  ansible.builtin.shell: |
    nohup bash -c 'sleep 60 && reboot' &>/dev/null &
  listen: reboot required
  async: 1
  poll: 0

- name: Update GRUB
  ansible.builtin.command: update-grub
  listen: grub updated

- name: Update initramfs
  ansible.builtin.command: update-initramfs -u -k all
  listen: initramfs updated

- name: Refresh boot tool
  ansible.builtin.command: proxmox-boot-tool refresh
  listen: kernel pinned
