---
# Kube-VIP version to deploy
# renovate: datasource=docker depName=ghcr.io/kube-vip/kube-vip
k3s_init_kube_vip_version: "v1.0.4"

# Directory for K3s server manifests
k3s_manifests_directory: /var/lib/rancher/k3s/server/manifests
