---
plugin: community.proxmox.proxmox
validate_certs: false
want_facts: true

keyed_groups:
  - key: proxmox_tags_parsed
    prefix: tag

groups:
  all_k3s: "'k3s' in (proxmox_tags_parsed|list)"
  masters: >-
    'k3s' in (proxmox_tags_parsed|list) and 'master' in (proxmox_tags_parsed|list)
  workers: >-
    'k3s' in (proxmox_tags_parsed|list) and 'worker' in (proxmox_tags_parsed|list)

compose:
  ansible_host: proxmox_ipconfig0.ip.split('/')[0]
