---
ansible_user: debian
ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

mgmt_iface: eth0
flannel_iface: eth1
vip_address: "10.9.9.99"

# Domain configuration
base_domain: "starktastic.net"
internal_domain: "internal.{{ base_domain }}"
argocd_url: "https://argocd.{{ internal_domain }}"
authentik_url: "https://auth.{{ base_domain }}"

argocd_repo_url: "https://github.com/Starktastic-Homelab/apps.git"

# NFS storage
nfs_server: "10.9.8.30"
nfs_base_path: "/mnt/apps/pv"

# K3s version to install
# renovate: datasource=github-releases depName=k3s-io/k3s
k3s_version: "v1.36.1+k3s1"
