---
- name: Create manifests directory
  ansible.builtin.file:
    path: "{{ k3s_manifests_directory }}"
    state: directory
    mode: "0700"

- name: Upload Kube-Vip RBAC Manifest
  ansible.builtin.get_url:
    url: https://kube-vip.io/manifests/rbac.yaml
    dest: "{{ k3s_manifests_directory }}/kube-vip-rbac.yaml"
    mode: "0444"

- name: Pull Kube-Vip image
  ansible.builtin.command: >-
    ctr image pull ghcr.io/kube-vip/kube-vip:{{ k3s_init_kube_vip_version }}
  register: k3s_init_kube_vip_pull
  changed_when: "'unpacking' in k3s_init_kube_vip_pull.stdout"

- name: Generate Kube-Vip DaemonSet
  ansible.builtin.command: >-
    ctr run --rm --net-host
      ghcr.io/kube-vip/kube-vip:{{ k3s_init_kube_vip_version }}
      vip /kube-vip manifest daemonset
      --interface {{ flannel_iface }} --address {{ vip_address }}
      --inCluster --taint --controlplane --services --arp --leaderElection
  register: k3s_init_kube_vip_daemonset_manifest
  changed_when: false

- name: Copy Kube-Vip DaemonSet to manifests directory
  ansible.builtin.copy:
    content: "{{ k3s_init_kube_vip_daemonset_manifest.stdout }}"
    dest: "{{ k3s_manifests_directory }}/kube-vip-daemonset.yaml"
    mode: "0444"
