---
- name: Create manifests directory
  ansible.builtin.file:
    path: "{{ k3s_manifests_directory }}"
    state: directory
    mode: "0700"
  tags:
    - kube-vip

- name: Download Kube-Vip RBAC Manifest
  ansible.builtin.get_url:
    url: https://kube-vip.io/manifests/rbac.yaml
    dest: "{{ k3s_manifests_directory }}/kube-vip-rbac.yaml"
    mode: "0444"
  tags:
    - kube-vip

- name: Pull Kube-Vip image
  ansible.builtin.command: >-
    ctr image pull ghcr.io/kube-vip/kube-vip:{{ k3s_init_kube_vip_version }}
  register: k3s_init_kube_vip_pull
  changed_when: "'unpacking' in k3s_init_kube_vip_pull.stdout"
  tags:
    - kube-vip

- name: Generate Kube-Vip Control Plane DaemonSet
  ansible.builtin.command: >-
    ctr run --rm --net-host
      ghcr.io/kube-vip/kube-vip:{{ k3s_init_kube_vip_version }}
      vip-cp /kube-vip manifest daemonset
      --interface {{ mgmt_iface }} --address {{ vip_address }}
      --inCluster --taint --controlplane --arp --leaderElection
      --prometheusHTTPServer :2112
  register: k3s_init_kube_vip_cp_manifest
  changed_when: false
  tags:
    - kube-vip

- name: Copy Kube-Vip Control Plane DaemonSet to manifests directory
  ansible.builtin.copy:
    content: "{{ k3s_init_kube_vip_cp_manifest.stdout | regex_replace('kube-vip-ds', 'kube-vip-cp') }}"
    dest: "{{ k3s_manifests_directory }}/kube-vip-cp.yaml"
    mode: "0444"
  tags:
    - kube-vip

- name: Generate Kube-Vip Services DaemonSet
  ansible.builtin.command: >-
    ctr run --rm --net-host
      ghcr.io/kube-vip/kube-vip:{{ k3s_init_kube_vip_version }}
      vip-svc /kube-vip manifest daemonset
      --interface {{ flannel_iface }} --address {{ vip_address }}
      --inCluster --services --arp --servicesElection
      --prometheusHTTPServer :2113
  register: k3s_init_kube_vip_svc_manifest
  changed_when: false
  tags:
    - kube-vip

- name: Copy Kube-Vip Services DaemonSet to manifests directory
  ansible.builtin.copy:
    content: "{{ k3s_init_kube_vip_svc_manifest.stdout | regex_replace('kube-vip-ds', 'kube-vip-svc') }}"
    dest: "{{ k3s_manifests_directory }}/kube-vip-svc.yaml"
    mode: "0444"
  tags:
    - kube-vip
