---
- name: Install and wait for the init node
  ansible.builtin.import_tasks: install.yml

- name: Set up Kube-Vip
  ansible.builtin.include_tasks: kube-vip.yml
  tags:
    - k3s
    - init
    - kube-vip

- name: Setup local kubeconfig
  ansible.builtin.include_tasks: kubeconfig.yml
  tags:
    - k3s
    - init
    - kubeconfig
