name: Deploy ser2net for Zigbee

on:
  push:
    branches:
      - main
    paths:
      - "roles/ser2net/**"
      - "ser2net.yml"

  workflow_dispatch:

jobs:
  deploy-ser2net:
    name: Deploy ser2net on Proxmox
    runs-on: self-hosted
    container:
      image: python:trixie

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Cache Pip Packages
        uses: actions/cache@v5.0.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Ansible and requirements
        run: pip install -r requirements.txt

      - name: Install sshpass for password auth
        run: apt-get update && apt-get install -y sshpass

      - name: Create Ansible Vault password file
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_pass

      - name: Run ser2net playbook
        run: |
          ansible-playbook -i inventory/hosts.yml \
            --vault-password-file .vault_pass \
            ser2net.yml
