---
name: Validate Ansible playbook
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'renovate.json'

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Cache Pip Packages
        uses: actions/cache@v5.0.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install ansible-lint
        run: pip install ansible-lint

      - name: Run ansible-lint
        run: |
          set +e
          OUTPUT=$(ansible-lint --offline --force-color . 2>&1)
          EXIT_CODE=$?
          set -e

          echo "### 🔍 Ansible Lint Results" >> $GITHUB_STEP_SUMMARY
          
          if [ $EXIT_CODE -eq 0 ]; then
             echo "✅ **Passed**" >> $GITHUB_STEP_SUMMARY
          else
             echo "❌ **Failed**" >> $GITHUB_STEP_SUMMARY
             echo '```term' >> $GITHUB_STEP_SUMMARY
             echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY
             echo '```' >> $GITHUB_STEP_SUMMARY
             exit 1
          fi

  syntax-check:
    name: Ansible Syntax Check
    runs-on: self-hosted
    container:
      image: python:trixie
    steps:
      - uses: actions/checkout@v6

      - name: Install Ansible and requirements
        run: pip install -r requirements.txt

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Create Ansible Vault password file
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_pass

      - name: Run Ansible Syntax Check
        env:
          PROXMOX_URL: ${{ secrets.PROXMOX_URL }}
          PROXMOX_USER: ${{ secrets.PROXMOX_USER }}
          PROXMOX_TOKEN_ID: ${{ secrets.PROXMOX_TOKEN_ID }}
          PROXMOX_TOKEN_SECRET: ${{ secrets.PROXMOX_TOKEN_SECRET }}
        run: |
          echo "### 🛠️ Syntax Check Results" >> $GITHUB_STEP_SUMMARY

          set +e
          OUTPUT=$(ansible-playbook -i inventory/proxmox.yml \
            --vault-password-file .vault_pass \
            --private-key private_key.pem \
            --syntax-check k3s.yml ser2net.yml 2>&1)
          EXIT_CODE=$?
          set -e

          if [ $EXIT_CODE -eq 0 ]; then
            echo "✅ **Valid**" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Invalid**" >> $GITHUB_STEP_SUMMARY
            echo '```term' >> $GITHUB_STEP_SUMMARY
            echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
